# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'RadonEye V2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RadonEye V2
  pod "SideMenu", '~> 6.4.8'
  pod 'XLPagerTabStrip', '~> 9.0'
#  pod 'Charts', '~> 5.0'

  target 'RadonEye V2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RadonEye V2UITests' do
    # Pods for testing
  end

end
